version: 0.0.1
language: russian



## Config

chr-price: 5000
mus-price: 5000
bud-price: 5000

chunk-tax:
  mus: 1
  chr: 1
  bud: 0.8

# for effects write in format "effectName:time:level!effectName2:time:level".
# if you don't want to give any effect write "".
event:
  kill:
    chr: "SPEED:10:2"
    mus: "INCREASE_DAMAGE:10:1"
    bud: "REGENERATION:10:1"

banned-food:
  chr: "bread!SPEED:3:1"
  mus: "cooked_porkchop!exp2/porkchop!exp2"
  bud: ""

## Structure

structure-enabled: true


## ColorString English

##english.

## ColorString Russian

russian:
  gui:
    town-religion: "&7Религия вашего города - %s"
    lore: "&7Чтобы удалить религию нажмите ПКМ (снова покупать)"
    lore-buy: "&7Нажмите ЛКМ для открытия меню покупки религии"
    lore-price: "&7Стоимость - %s"
    title: "&fМеню выбора религии"

    rebuild-temple: "ВОССТАНОВИТЕ ХРАМ!"

    first-chr: "Первая церковь"
    first-mus: "Первая мечеть"
    first-bud: "Первый храм"

    second-chr: "Вторая церковь"
    second-mus: "Вторая мечеть"
    second-bud: "Второй храм"

  new-chr-town: "&fТеперь религия вашего города &bХристианство"
  new-mus-town: "&fТеперь религия вашего города &bМусульманство"
  new-bud-town: "&fТеперь религия вашего города &bБуддизм"
  mus: "&bМусульманство"
  chr: "&bХристианство"
  bud: "&bБуддизм"
  religion: "&eРелигия"
  religion-deleted: "&fРелигия вашего города была удалена"
  not-enough-money: "&fНедостаточно средств!"

  religion-reset: "&fРелигия города %s была удалена!"
  religion-change: "&fРелигия города %s была изменена на %r"

  wrong-access: "&fНедостаточно прав!"
  wrong-args: "&fНеверные аргументы!"

  structure-error-chunk: "&fХрам должен располагаться в одном чанке внутри вашего города!"
  structure-error-place: "&fТерритория должна быть расчищена!"
  structure-error-religion-exists: "&fУ вашего города уже сть религия!"
