version: 0.1.1
language: russian



## Config

chr-price: 5000
mus-price: 5000
bud-price: 5000

chunk-tax:
  mus: 1
  chr: 1
  bud: 0.8

# GUI icons

materials:
  main: "TOTEM_OF_UNDYING"

  chr-main: "WHEAT"
  mus-main: "GOLDEN_SWORD"
  bud-main: "NETHER_STAR"

  chr-1: "LAPIS_BLOCK"
  chr-2: "GOLD_BLOCK"

  mus-1: "IRON_BLOCK"
  mus-2: "NETHER_BRICK"

  bud-1: "GLASS"
  bud-2: "ENCHANTED_BOOK"

# for effects write in format "effectName:time:level/effectName2:time:level".
# if you don't want to give any effect write "".
event:
  kill:
    chr: "SPEED:10:2"
    mus: "INCREASE_DAMAGE:10:1"
    bud: "REGENERATION:10:1"

banned-food:
  chr: ["BREAD!SPEED:3:1/REGENERATION:10:1"]
  mus: ["COOKED_PORKCHOP!exp:1:20", "PORKCHOP!exp:1:20"]
  bud: []

## Structure

structure-enabled: true


## ColorString English

##english.

## ColorString Russian

russian:
  gui:
    town-religion: "&7Религия вашего города - %s"
    lore: "&7Чтобы удалить религию нажмите ПКМ (снова покупать)"
    lore-buy: "&7Нажмите ЛКМ для открытия меню покупки религии"
    lore-price: "&7Стоимость - %s"
    title: "&8Меню выбора религии"

    rebuild-temple: "ВОССТАНОВИТЕ ХРАМ!"

    1-chr: "Первая церковь"
    1-mus: "Первая мечеть"
    1-bud: "Первый храм"

    2-chr: "Вторая церковь"
    2-mus: "Вторая мечеть"
    2-bud: "Второй храм"

  new-chr-town: "&fТеперь религия вашего города &bХристианство"
  new-mus-town: "&fТеперь религия вашего города &bМусульманство"
  new-bud-town: "&fТеперь религия вашего города &bБуддизм"
  mus: "&bМусульманство"
  chr: "&bХристианство"
  bud: "&bБуддизм"
  religion: "&eРелигия"
  religion-deleted: "&fРелигия вашего города была удалена"
  not-enough-money: "&fНедостаточно средств!"

  religion-reset: "&fРелигия города %s была удалена!"
  religion-change: "&fРелигия города %s была изменена на %r"

  wrong-access: "&fНедостаточно прав!"
  wrong-args: "&fНеверные аргументы!"

  structure-error-chunk: "&fХрам должен располагаться в одном чанке внутри вашего города!"
  structure-error-place: "&fТерритория должна быть расчищена!"
  structure-error-religion-exists: "&fУ вашего города уже сть религия!"

  structure-destroy-finished: "&fСтруктура была удалена!"

